name: Development

on:
  push:
    branches:
      - master

jobs:
  default:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://dev.domain.app
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Use Node 18.x
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: yarn.lock
          cache: "yarn"

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Run Lint
      - name: Run Lint
        run: yarn lint

      # Create Development Build
      - name: Create Development Build
        run: yarn build:dev

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist
